name: Build development tools

on: push

jobs:
  linux:
    name: Building tools on Linux

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aminya/setup-cpp@v1
        with:
          compiler: gcc-13

      - name: Base tools
        run: bash ubuntu/base.sh

      - name: Criterion
        run: bash ubuntu/criterion.sh

      - name: GoogleTest
        run: bash ubuntu/googletest.sh

      - name: zlib
        run: bash ubuntu/zlib.sh

      - name: FFTW
        run: bash ubuntu/fftw.sh

      - name: libpng
        run: bash ubuntu/libpng.sh

      - name: libdeflate
        run: bash ubuntu/libdeflate.sh

      - name: isa-l
        run: bash ubuntu/isal.sh

      - name: FFmpeg
        run: bash ubuntu/ffmpeg.sh

  macos:
    name: Building tools on MacOS

    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Base tools
        run: bash macos/base.sh
  
      # - name: Criterion
        # run: bash macos/criterion.sh
  
      # - name: GoogleTest
        # run: bash macos/googletest.sh
  
      # - name: zlib
        # run: bash macos/zlib.sh
  
      # - name: FFTW
        # run: bash macos/fftw.sh
  
      # - name: libpng
        # run: bash macos/libpng.sh
  
      # - name: libdeflate
        # run: bash macos/libdeflate.sh
  
      - name: isa-l
        run: bash macos/isal.sh
  
      # - name: FFmpeg
        # run: bash macos/ffmpeg.sh
