name: Build development tools

on: push

jobs:
  linux:
    name: Building tools on Linux

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install compilers
        uses: aminya/setup-cpp@v1
        with:
          compiler: clang-18

      - name: Install base tools
        run: bash ubuntu/base.sh

      - name: GoogleTest
        run: bash ubuntu/googletest.sh

      - name: zlib
        run: bash ubuntu/zlib.sh
