name: Build Docker images

on:
  workflow_dispatch:
  push:
    paths:
      - 'images/Dockerfile'
      - '.github/workflows/docker.yml'
      - 'ubuntu/*.sh'

jobs:
  build:
    name: "Building ${{ matrix.image.os_type }} ${{ matrix.edition }} devtool ${{ matrix.image.arch }}"

    strategy:
      fail-fast: true

      matrix:
        image:
          - { arch: amd64, os: ubuntu, os_type: linux, os_version: 22.04 }

        edition:
          - default
          - full

    runs-on: ${{ matrix.image.os }}-${{ matrix.image.os_version }}

    env:
      IMAGE_NAME: "se-c-cpp-prog/devtool:${{ matrix.image.os_type }}-${{ matrix.image.arch }}-${{ matrix.edition }}"
      TAR_NAME: "devtool-${{ matrix.image.os_type }}-${{ matrix.image.arch }}-${{ matrix.edition }}.tar"

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --tag "${{ env.IMAGE_NAME }}" --build-arg DEVTOOL_EDITION=${{ matrix.edition }} -f images/${{ matrix.image.os_type }}/Dockerfile .

      - name: Save Docker image
        run: docker save "${{ env.IMAGE_NAME }}" > "${{ env.TAR_NAME }}"

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image.os_type }}-${{ matrix.image.arch }}-${{ matrix.edition }}
          path: ${{ env.TAR_NAME }}
          compression-level: 9
          retention-days: 14
