name: Build Docker images

on:
  workflow_dispatch:
  push:
    paths:
      - 'images/Dockerfile'
      - '.github/workflows/docker.yml'
      - 'ubuntu/*.sh'

jobs:
  build:
    name: "Building devtool"
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "se-c-cpp-prog/devtool:ubuntu"

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build --tag "${{ env.IMAGE_NAME }}" -f images/Dockerfile .
