name: Release development tools
run-name: ${{ inputs.release_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
        description: "Release tag name."
      release_name:
        required: true
        type: string
        description: "Release name."
      testing_release:
        required: true
        type: boolean
        description: "Is this release is in testing purpose?"

jobs:
  stage1_init_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/create-release@v1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          prerelease: ${{ inputs.testing_release }}
          release_name: ${{ inputs.release_name }}
          tag_name: ${{ inputs.tag_name }}

  stage2_build_artifacts:
    needs: stage1_init_release

    strategy:
      fail-fast: true

      matrix:
        toolchain:
          - { name: Linux,   os: ubuntu,    os_version: 22.04, compiler: gcc-13,        archive_file_ext: tar.gz }
          - { name: Windows, os: windows,   os_version: 2022,  compiler: msvc-2022,     archive_file_ext: zip }
          - { name: macOS,   os: macos,     os_version: 14,    compiler: appleclang-18, archive_file_ext: zip }

        library:
          - { name: googletest, version: 1.15.2 }
          - { name: zlib,       version: 1.3.1 }
          - { name: fftw,       version: 3.3.10 }
          - { name: libpng,     version: 1.6.43 }
          - { name: libdeflate, version: 1.21 }
          - { name: ffmpeg,     version: 6.1 }

    runs-on: ${{ matrix.toolchain.os }}-${{ matrix.toolchain.os_version }}

    steps:
      - uses: actions/checkout@v4

      - uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          vcvarsall: ${{ contains(matrix.toolchain.os, 'windows') }}
          ninja: true
          cmake: true

      - uses: ilammy/setup-nasm@v1.5.1
        if: ${{ matrix.toolchain.os == 'windows' }}

      - name: Install UNIX base tools
        if: ${{ matrix.toolchain.os != 'windows' }}
        run: bash ${{ matrix.toolchain.os }}/base.sh

      - name: Build ${{ matrix.library.name }} (UNIX)
        if: ${{ matrix.toolchain.os != 'windows' }}
        run: bash ${{ matrix.toolchain.os }}/${{ matrix.library.name }}.sh

      - name: Build ${{ matrix.library.name }}
        if: ${{ matrix.toolchain.os == 'windows' }}
        run: powershell ${{ matrix.toolchain.os }}/${{ matrix.library.name }}.ps1

      - name: Upload ${{ matrix.library.name }} artifact archive
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ARCHIVE_BASENAME: ${{ matrix.toolchain.os }}-${{ matrix.library.name }}-${{ matrix.library.version }}.${{ matrix.toolchain.archive_file_ext }}
        with:
          file: ${{ env.ARCHIVE_BASENAME }}
          asset_name: ${{ env.ARCHIVE_BASENAME }}
          tag: ${{ inputs.tag_name }}
